- name: Updating Apt Cache
  become: yes
  apt:
    update_cache: yes

- name: "Configure Timezone"
  become: yes
  shell: |
          echo "Europe/Tallinn" > /etc/timezone && \
          dpkg-reconfigure -f noninteractive tzdata 

- name: "support install postfix non-interactively"
  become: yes
  shell: |
          echo "postfix postfix/mailname string {{ main_hostname }}" | debconf-set-selections
          echo "postfix postfix/main_mailer_type string 'Internet Site'" | debconf-set-selections
          apt-get -y install postfix

- name: Replace hostname in postfix config
  become: yes
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^myhostname'
    line: myhostname = {{ main_hostname }}

- name: Update or Create sasl password file
  become: yes
  lineinfile:
    path: /etc/postfix/sasl_passwd
    create: yes
    line: "{{ item.name }}  {{ item.smtp_cred }}"
  with_items: 
    - "{{ domainlist }}"


- name: Replace relayhost in postfix config
  become: yes
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^relayhost'
    line: relayhost = [smtp.mailgun.org]:587

- name: Insert/Update lines in postfix config
  become: yes
  blockinfile:
    path: /etc/postfix/main.cf
    block: |
      smtp_sasl_auth_enable = yes
      smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
      smtp_sasl_security_options = noanonymous
      smtp_sender_dependent_authentication = yes

- name: Create Postfix Hash map
  become: yes
  shell: |
          postmap /etc/postfix/sasl_passwd
          rm /etc/postfix/sasl_passwd

- name: Set Postfix db permissions
  become: yes
  file:
    path: /etc/postfix/sasl_passwd.db
    mode: '0600'

- name: Restart Postfix Service
  become: yes
  systemd:
    name: postfix
    state: restarted
    enabled: yes

- name: Updating Apt Cache
  become: yes
  apt:
    update_cache: yes

- name: Install certbot
  become: yes
  apt:
    state: present
    pkg:
      - certbot

- name: Generate Certificates for domains
  become: yes
  shell: |
          certbot certonly  --standalone -d {{ item.mail_domain }}  --non-interactive --agree-tos -m {{ item.webmaster }}
  with_items: 
    - "{{ domainlist }}"

- name: Create Postfix SSL Map
  become: yes
  blockinfile:
    create: yes
    path: /etc/postfix/ssl_map
    block: |
      {{ item.mail_domain }}
          /etc/letsencrypt/live/{{ item.mail_domain }}/privkey.pem
          /etc/letsencrypt/live/{{ item.mail_domain }}/fullchain.pem
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.mail_domain }}"
  with_items: 
    - "{{ domainlist }}"

- name: Hash Postfix SSL map
  become: yes
  shell: sudo postmap -F hash:/etc/postfix/ssl_map

