apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: root-registry
  namespace: argocd

spec:
  sourceRepos:
    - https://github.com/nebed/personal-sandbox.git

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'