apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: argocd
  annotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=true"
  name: argocd-rbac-cm
data:
  policy.default: ''
  policy.csv: |
{{ tpl (.Files.Get "rbac.csv.tpl") . | indent 4 }}
  scopes: '[groups, email]'