registry:
  services:
    argocd-rbac:
      repo: personal-sandbox
      namespace: argocd
      path: gcp/projects/personal-projects/charts/argocd-rbac
      overrideNamespace: true
    sealed-secrets:
      repo: personal-sandbox
      namespace: sealed-secrets
      path: gcp/projects/personal-projects/charts/sealed-secrets