namespaceOverride: "argocd"
redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: ingress-nginx-public
    tls: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

configs:
  params:
    server.insecure: true
  cm:
    exec.enabled: true
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: ${dex_github_client_id}
            clientSecret: $argocd-dex:dex.github.clientSecret
            orgs:
            - name: nebed
    resource.compareoptions: |
      ignoreResourceStatusField: all

global:
  domain: argocd.sandbox.nebed.io
