- name: Restart Postfix Service
  become: yes
  systemd:
    name: postfix
    state: restarted
    enabled: yes

- name: Restart Dovecot Service
  become: yes
  systemd:
    name: dovecot
    state: restarted
    enabled: yes

- name: Reload Nginx Service
  become: yes
  systemd:
    name: nginx
    state: reloaded
    enabled: yes

- name: Restart Nginx Service
  become: yes
  systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Restart Redis Service
  become: yes
  systemd:
    name: redis
    state: restarted
    enabled: yes

- name: Restart Rspamd Service
  become: yes
  systemd:
    name: rspamd
    state: restarted
    enabled: yes