{{ range $serviceName, $serviceDef := .Values.services }}
{{- $environment := deepCopy $.Values.global.environment }}
{{- if not (or (index $serviceDef (printf "%sRef" $environment.name)) $serviceDef.ref) }}
{{- continue }}
{{- end }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ ternary (printf "%s-%s" $serviceName $environment.name) $serviceName (has $environment.name (list "dev" "hotfix" "lab" "staging")) }}
---
{{ end }}